version: "3"

services:
  database:
    image: postgres:9.6.15-alpine
    restart: always
    env_file:
     - ./postgres.env
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  object-store-api:
    image: img_object_store_api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./object_store_api.env

  minio:
    image: minio/minio
    container_name: minio
    env_file:
      - ./minio.env
    ports:
      - "9000:9000"
    command: server /data

volumes:
  database-data:
