spring:
  datasource:
 #   url: jdbc:postgresql://localhost:5532/object_store
 #   username: postgres
 #   password: postgres
  servlet:
    multipart:
      max-file-size:  128KB   
      max-request-size:  128KB
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: schema-change
    liquibase-schema: object_store
  jpa:
    open-in-view: false
minio:
  scheme:  http
  host:  localhost
  port:  9000
  accessKey:  minio	
  secretKey:  minio123
crnk:
  pathPrefix: /api/v1
  domainName: ""
  defaultPageLimit: 20
  maxPageLimit: 1000
  allow-unknown-attributes: true
  # The "include" query-string param is handled by our code and incorporated into the database
  # query, so we don't let Crnk automatically call findOneTarget for each null relation.
  config.lookup.behavior.default: NONE
  jpa.enabled: false
objectstore:
  defaultLicenceURL: https://open.canada.ca/en/open-government-licence-canada
  defaultCopyright: Copyright Government of Canada
  defaultCopyrightOwner: Government of Canada
  defaultUsageTerms: Government of Canada Usage Term
logging:
  level:
    Root: INFO
    # Reduce the logging from the rsql-jpa library, which is otherwise too excessive:
    com.github.tennaito.rsql: ERROR
keycloak:
  enabled: false
  realm: dina
  auth-server-url: http://${KEYCLOAK_HOST_IP}:8080/auth
  ssl-required: none
  resource: objectstore
  public-client: true
  bearer-only: true
  principal-attribute: preferred_username

  # All endpoints require a logged-in user with the "user" role.
  security-constraints:
    - auth-roles:
      - user
      security-collections:
        - patterns:
          - /*
  