spring:
  datasource:
    url: jdbc:postgresql://localhost:5532/object_store
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size:  128KB   
      max-request-size:  128KB
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: schema-change
minio:
  scheme:  http
  host:  localhost
  port:  9000
  accessKey:  minio	
  secretKey:  minio123
crnk:
  pathPrefix: /api
  domainName: ""
  defaultPageLimit: 20
  maxPageLimit: 1000
  allow-unknown-attributes: true
  # The "include" query-string param is handled by our code and incorporated into the database
  # query, so we don't let Crnk automatically call findOneTarget for each null relation.
  config.lookup.behavior.default: NONE
  jpa.enabled: false
